import Head from "next/head";
import {
  VStack,
  Center,
  Container,
  Heading,
  Button,
  HStack,
} from "@chakra-ui/react";
import { TypeAnimation } from "react-type-animation";
import NextLink from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>MapAi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HStack direction="row" h="90vh">
        <Container maxW="6xl">
          <VStack gap="50px" direction="column">
            <Heading alignItems="left">
              Sometimes all we need is a map 🗺️
            </Heading>
            <Heading>Create in-depth roadmaps to learn how to:</Heading>
          </VStack>
          <Container maxW="6xl" mt="50px" p="0">
            <Center>
              <Heading fontSize="20px">
                <TypeAnimation
                  sequence={[
                    "Learn Arabic",
                    1000,
                    "Become an fullstack engineer",
                    1000,
                    "Get a freelance job",
                    1000,
                    "Create a python script",
                    1000,
                    "Run for longer",
                    1000,
                    "Get good at speaking",
                    1000,
                    "Meet cool people",
                    1000,
                    "Move to Dubai",
                    1000,
                  ]}
                  speed={30}
                  deletionSpeed={70}
                  style={{ fontSize: "2em" }}
                  wrapper="span"
                  repeat={Infinity}
                />
              </Heading>
            </Center>
          </Container>
          <Center mt="40px">
            <NextLink href="/createmap">
              <Button bg="#4FAD27" color="white" size="lg">
                {" "}
                Create a Roadmap
              </Button>
            </NextLink>
          </Center>
        </Container>
      </HStack>
    </>
  );
}
