import Head from "next/head";
import {
  VStack,
  Center,
  Text,
  Heading,
  Button,
  Input,
  FormControl,
  Box,
  Container,
} from "@chakra-ui/react";
import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [learn, setLearn] = useState("");
  const [data, setData] = useState("");

  const handleInputFormChange = (event: any) => {
    setLearn(event.target.value);
  };

  const gptPostClient = axios.create({
    baseURL: "https://api.openai.com/v1/completions",
  });

  const returnResults = async () => {
    setIsLoading(true);
    const prompt =
      "You are an Ivy League University professor and your specialty is to encourage a fair and balanced debate. You are mediating a debate between Mr.X and Mr.Y. Furthermore, you will play the part of Mr.X, Mr.Y and the professor in your responses. The debate will go on for 3 responses, with a final summary of positions. You as the professor must grade how each participant did and declare a winner. Mr.X and Mr.Y are passionate about their positions they will be defending, and as the professor, it is your job to keep the debate on point. The debate will be on:" +
      learn +
      ". When the debate is over say, this brings an end to the debate, thank you for listening! Lastly make sure that your responses to each side are creative and not repetitive.";
    gptPostClient
      .post(
        "",
        {
          model: "text-davinci-003",
          prompt: prompt,
          max_tokens: 1000,
          temperature: 0,
        },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + process.env.APIKEY,
          },
        }
      )
      .then((resp) => {
        setData(resp.data.choices[0].text.trim());
      });
    setTimeout(() => {
      setIsLoading(false);
    }, 7000);
  };

  return (
    <>
      <Head>
        <title>DEB(AI)TE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <VStack w="5xl" h="100vh" gap="50px">
          <Heading fontSize="30px" mt="10">
            Two sides, Mr. X and Mr. Y. vigorously debate the question:
          </Heading>
          <FormControl id="prompt" fontSize={"2xl"}>
            <Box>
              <Input
                placeholder="Is God real?"
                size="lg"
                onChange={handleInputFormChange}
                value={learn}
              />
            </Box>
          </FormControl>
          <Heading fontSize="20px" mt="10">
            Mediated by a world class professor.
          </Heading>
          <Button
            bg="black"
            color="white"
            size="lg"
            p="20px"
            onClick={returnResults}
            isLoading={isLoading}
            _hover={{
              background: "white",
              color: "red",
            }}
          >
            {" "}
            Load Debate
          </Button>
          <Box padding="6" bg="white" borderRadius="lg">
            <Text fontSize="20px" whiteSpace="pre-wrap">
              {data}
            </Text>
          </Box>
        </VStack>
      </Center>
    </>
  );
}
